---
title: "Step6.02.Rmd"
output: html_document
date: "2025-05-22"
---
---
# Install required packages
install.packages("dplyr") 

# Load required libraries
library(MASS)  # for stepAIC
library(dplyr)

# Load the dataset
data <- read.csv("/Users/valerievera/Library/CloudStorage/OneDrive-UniversityofSouthCarolina/Documents/PhD Program/Dissertation/Dissertation - Phase 1/R Data Analysis/Dissertation/dissertation_data.csv")

# View summary of missing values per column
colSums(is.na(data))

# Remove rows with any missing variables
cleaned_data <- na.omit(data)
dim(cleaned_data)  # Returns number of rows and columns
summary(cleaned_data)

# Define variables
content_vars <- c(
  "addiction_relapsing", "addiction_sobriety", "scars_healed", "signaling_abstract", "trigger_warning"
)

# Start with only main effects
main_effects <- as.formula(
  paste("availability ~", paste(content_vars, collapse = " + "))
)

main_model <- glm(main_effects, data = model_data, family = binomial)

# Use scope to allow 2-way interactions as candidates
interaction_scope <- as.formula(
  paste("~ (", paste(content_vars, collapse = " + "), ")^2")
)

step_model <- stepAIC(main_model, scope = interaction_scope, direction = "both")
summary(step_model)


exp(coef(step_model))           # Odds ratios
exp(confint(step_model))        # 95% CI for ORs

